# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get cell number from x and y coordinates
#' 
#' NB: This source code is taken from \code{raster} package with a slight 
#' change of name.
#' 
#' @param ncols Number of colums of the raster grid.
#' 
#' @param nrows Number of rows of the raster grid.
#' 
#' @param xmin Minimal value of x coordinates.
#' 
#' @param xmax Maximal value of x coordinates.
#' 
#' @param ymin Minimal value of y coordinates.
#' 
#' @param ymax Maximal value of y coordinates.
#' 
#' @param x Vector of x coordinates.
#' 
#' @param y Vector of y coordinates.
#' 
#' @export
doCellFromXY <- function(ncols, nrows, xmin, xmax, ymin, ymax, x, y) {
    .Call('_simutils_doCellFromXY', PACKAGE = 'simutils', ncols, nrows, xmin, xmax, ymin, ymax, x, y)
}

#' Get x and y coordinates from cell ID number.
#' 
#' NB: This source code is taken from \code{raster} package with a slight 
#' change of name.
#' 
#' @param ncols Number of colums of the raster grid.
#' 
#' @param nrows Number of rows of the raster grid.
#' 
#' @param xmin Minimal value of x coordinates.
#' 
#' @param xmax Maximal value of x coordinates.
#' 
#' @param ymin Minimal value of y coordinates.
#' 
#' @param ymax Maximal value of y coordinates.
#' 
#' @param cell Vector of cell ID numbers.
#' 
#' @export
doXYFromCell <- function(ncols, nrows, xmin, xmax, ymin, ymax, cell) {
    .Call('_simutils_doXYFromCell', PACKAGE = 'simutils', ncols, nrows, xmin, xmax, ymin, ymax, cell)
}

